# Generated by Django 4.1.3 on 2022-11-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='img',
            field=models.ImageField(upload_to='webapp/static/images/upload/movies/'),
        ),
    ]
