# Generated by Django 4.1.3 on 2022-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_geeksmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='img',
            field=models.ImageField(upload_to='webapp/static/images/upload/profile_picture/'),
        ),
    ]
