# Generated by Django 4.1.3 on 2022-11-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_geeksmodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='webapp/static/images/upload/movies/')),
            ],
        ),
    ]
